import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header";
import Main from "../components/main";
import Wallet from "../components/wallet";

export default function Home() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Blockchain Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Wallet />
        <Main />
      </main>
    </section>
  );
}
